#!/usr/bin/env bash

sudo dnf copr enable derisis13/ani-cli
sudo dnf install ani-cli fontconfig-devel

mkdir -p ~/.local/share/fonts
cd ~/.local/share/fonts
wget https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Meslo.zip
unzip Meslo.zip
fc-cache -fv

