#!/usr/bin/env bash

sudo dnf install flatpak
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
sudo flatpak install flathub com.discordapp.Discord
sudo flatpak install flathub com.slack.Slack
sudo flatpak install flathub io.dbeaver.DBeaverCommunity
sudo flatpak install flathub com.brave.Browser

