#!/usr/bin/env bash

git clone -b v0.11.0 https://github.com/neovim/neovim.git $HOME/personal/neovim

sudo dnf install gcc cmake ripgrep gettext lua5.1 ripgrep maim nitrogen picom xclip zsh

cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

git clone https://github.com/ThePrimeagen/harpoon.git $HOME/personal/harpoon
cd $HOME/personal/harpoon
git fetch
git checkout harpoon2

git clone https://github.com/ThePrimeagen/vim-apm.git $HOME/personal/vim-apm
git clone https://github.com/ThePrimeagen/vim-with-me.git $HOME/personal/vim-with-me
git clone https://github.com/ThePrimeagen/vim-arcade.git $HOME/personal/vim-arcade
git clone https://github.com/ThePrimeagen/caleb.git $HOME/personal/caleb
git clone https://github.com/nvim-lua/plenary.nvim.git $HOME/personal/plenary

wget https://luarocks.org/releases/luarocks-3.11.1.tar.gz
tar zxpf luarocks-3.11.1.tar.gz
cd luarocks-3.11.1
./configure && make && sudo make install
sudo luarocks install luacheck
