#!/usr/bin/env bash

sudo dnf install -y nodejs npm

npm config set prefix ~/.local/npm
npm install -g n
n lts

export PATH="$HOME/.local/npm/bin:$PATH"

curl -fsSL https://deno.land/install.sh | sh
curl -fsSL https://bun.sh/install | bash

